server "heinrichtaver.com" {
  listen on * tls port 443
  gzip-static
  root "/htdocs/com.heinrichtaver.www"

  tls {
    certificate "/etc/ssl/acme/com.heinrichtaver.fullchain.pem"
    key "/etc/ssl/acme/private/com.heinrichtaver.key"
  }

  location "/.well-known/acme-challenge/*" {
    root "/acme"
    request strip 2
  }
}

server "www.heinrichtaver.com" {
  listen on * tls port 443

  tls {
    certificate "/etc/ssl/acme/com.heinrichtaver.fullchain.pem"
    key "/etc/ssl/acme/private/com.heinrichtaver.key"
  }

  block return 301 "https://heinrichtaver.com$REQUEST_URI"
}

server "heinrichtaver.com" {
  alias "www.heinrichtaver.com"
  listen on * port 80
  block return 301 "https://heinrichtaver.com$REQUEST_URI"
}
