server "heinrichtaver.com" {
  listen on * port 80
  gzip-static
  root "/htdocs/com.heinrichtaver.www"
}

server "www.heinrichtaver.com" {
  listen on * port 80
  block return 301 "http://heinrichtaver.com$REQUEST_URI"
}
